In [1]:
import numpy as np
from scipy.ndimage._filters import _gaussian_kernel1d

In [4]:
# Generate a 1D Gaussian kernel

Gauss_kernel1D = _gaussian_kernel1d(sigma=2, order=0, radius=8)
Gauss_kernel1D

array([6.69162896e-05, 4.36349021e-04, 2.21596317e-03, 8.76430436e-03,
       2.69959580e-02, 6.47599366e-02, 1.20987490e-01, 1.76035759e-01,
       1.99474648e-01, 1.76035759e-01, 1.20987490e-01, 6.47599366e-02,
       2.69959580e-02, 8.76430436e-03, 2.21596317e-03, 4.36349021e-04,
       6.69162896e-05])

In [3]:
# Generate a 1D Derivative of Gaussian kernel, using actual DoG formula

DoG_kernel1D = _gaussian_kernel1d(sigma=2, order=1, radius=8)
DoG_kernel1D

array([ 0.00013383,  0.00076361,  0.00332394,  0.01095538,  0.02699596,
        0.04856995,  0.06049374,  0.04400894,  0.        , -0.04400894,
       -0.06049374, -0.04856995, -0.02699596, -0.01095538, -0.00332394,
       -0.00076361, -0.00013383])

In [7]:
# Generate a 1D Derivative of Gaussian kernel, using the numerical derivative approximation of the Gaussian kernel

DoG_kernel1D = np.gradient(Gauss_kernel1D)
pos_indices, neg_indices = np.where(DoG_kernel1D > 0), np.where(DoG_kernel1D < 0)
DoG_kernel1D[pos_indices] = DoG_kernel1D[pos_indices] / np.sum(DoG_kernel1D[pos_indices])
DoG_kernel1D[neg_indices] = DoG_kernel1D[neg_indices] / np.abs(np.sum(DoG_kernel1D[neg_indices]))

DoG_kernel1D

array([ 0.0019664 ,  0.00571941,  0.02216379,  0.06594879,  0.14902522,
        0.25014646,  0.29614639,  0.20888355,  0.        , -0.20888355,
       -0.29614639, -0.25014646, -0.14902522, -0.06594879, -0.02216379,
       -0.00571941, -0.0019664 ])